cabal-version: 3.0
name:          effective-bench
version:       0.1.0.0
synopsis:      Benchmarks for Haskell effect handler libraries
description:
    A benchmark for comparing Haskell effect handler libraries.
    The test cases are adapted from [heftia-effects](https://github.com/sayo-hs/heftia/tree/master/benchmark)
    but with `O2` enabled and `NOINLINE` pragrams removed.
    Each testcase/library implementation lives in its own module so GHC
    compiles it separately to make sure that each library receives the
    same simplification ticks.
license:       BSD-3-Clause
license-file:  LICENSE
author:        Zhixuan Yang, Nicolas Wu
maintainer:    Zhixuan Yang, Nicolas Wu
category:      Control
build-type:    Simple

extra-doc-files:
    CHANGELOG.md

tested-with: GHC == 9.10.1

common warnings
    ghc-options: -Wall

common bench-common
    default-language: GHC2021
    default-extensions:
        AllowAmbiguousTypes,
        BlockArguments,
        DataKinds,
        LambdaCase,
        PackageImports,
        PartialTypeSignatures,
        TemplateHaskell,
        MonoLocalBinds,
        TypeApplications,
        CPP
    ghc-options:
        -Wall
        -O2
        -rtsopts
        -threaded
        -fconstraint-solver-iterations=16
        -freduction-depth=0
        -Wno-partial-type-signatures
        -dcore-lint
    build-depends:
        base == 4.20.0.0,
        tasty-bench == 0.4.1

common bench-common-o0
    default-language: GHC2021
    default-extensions:
        AllowAmbiguousTypes,
        BlockArguments,
        DataKinds,
        LambdaCase,
        PackageImports,
        PartialTypeSignatures,
        TemplateHaskell,
        MonoLocalBinds,
        TypeApplications,
        CPP
    ghc-options:
        -Wall
        -O0
        -rtsopts
        -threaded
        -fconstraint-solver-iterations=16
        -freduction-depth=0
        -Wno-partial-type-signatures
        -dcore-lint
    build-depends:
        base == 4.20.0.0,
        tasty-bench == 0.4.1

common bench-heftia
    build-depends:
        data-effects == 0.4.2.0,
        heftia-effects == 0.7.0.0

common bench-freer-simple
    build-depends:
        freer-simple == 1.2.1.2

common bench-polysemy
    build-depends:
        polysemy == 1.9.2.0

common bench-fused-effects
    build-depends:
        fused-effects == 1.1.2.7

common bench-effectful
    build-depends:
        effectful == 2.5.1.0

common bench-eff
    build-depends:
        eff == 0.0.0.0

common bench-mpeff
    build-depends:
        mpeff == 0.1.0.0

common bench-mtl
    build-depends:
        mtl == 2.3.1

common bench-logict
    build-depends:
        logict == 0.8.2.0

common bench-list-t
    build-depends:
        list-t == 1.0.5.7

common bench-handrolled
    build-depends:
        transformers == 0.6.1.1

common bench-effective
    build-depends:
        effective

common bench-effective-naive
    build-depends:
        effective-naive

benchmark with-o2
    import:         bench-common, bench-heftia, bench-freer-simple, bench-polysemy,
                    bench-fused-effects, bench-effectful, bench-eff, bench-mpeff, bench-mtl,
                    bench-logict, bench-list-t, bench-handrolled, bench-effective, bench-effective-naive
    type:           exitcode-stdio-1.0
    hs-source-dirs: bench
    main-is:        Main.hs
    cpp-options:    -DDISABLE_VERY_DEEP
    -- If your machine has really a lot of memory you can try removing `-DDISABLE_VERY_DEEP`.
    other-modules:
        Bench.Mpeff
        Bench.Catch.VeryDeep.Effective
        Bench.Catch.VeryDeep.EffectiveFullyStaged
        Bench.Catch.VeryDeep.FreerSimple
        Bench.Catch.VeryDeep.Mtl
        Bench.Countdown.VeryDeep.Effective
        Bench.Countdown.VeryDeep.EffectiveFullyStaged
        Bench.Countdown.VeryDeep.FreerSimple
        Bench.Countdown.VeryDeep.Mtl
        Bench.Local.VeryDeep.Effective
        Bench.Local.VeryDeep.EffectiveFullyStaged
        Bench.Local.VeryDeep.FreerSimple
        Bench.Local.VeryDeep.Mtl
        Bench.Nondet.VeryDeep.Effective
        Bench.Nondet.VeryDeep.EffectiveFullyStaged
        Bench.Nondet.VeryDeep.FreerSimple
        Bench.Nondet.VeryDeep.MtlLogict
        Bench.EffectiveFullyStaged
        --
        Bench.Catch.Eff
        Bench.Catch.Effectful
        Bench.Catch.FreerSimple
        Bench.Catch.FusedEffects
        Bench.Catch.Heftia
        Bench.Catch.Mpeff.Safe
        Bench.Catch.Mpeff.Unsafe
        Bench.Catch.Mtl
        Bench.Catch.Polysemy
        Bench.Catch.Handrolled
        Bench.Catch.Effective
        Bench.Catch.EffectiveFullyStaged
        Bench.Catch.EffectiveLightlyStaged
        Bench.Catch.EffectiveNaive
        --
        Bench.Countdown.Eff
        Bench.Countdown.Effective
        Bench.Countdown.EffectiveFullyStaged
        Bench.Countdown.EffectiveLightlyStaged
        Bench.Countdown.EffectiveNaive
        Bench.Countdown.Effectful
        Bench.Countdown.FreerSimple
        Bench.Countdown.FusedEffects
        Bench.Countdown.Handrolled
        Bench.Countdown.Heftia
        Bench.Countdown.Mpeff.Safe
        Bench.Countdown.Mpeff.Unsafe
        Bench.Countdown.Mtl
        Bench.Countdown.Polysemy
        --
        Bench.Local.Effectful
        Bench.Local.Eff
        Bench.Local.Effective
        Bench.Local.EffectiveFullyStaged
        Bench.Local.EffectiveLightlyStaged
        Bench.Local.EffectiveNaive
        Bench.Local.FreerSimple
        Bench.Local.FusedEffects
        Bench.Local.Handrolled
        Bench.Local.Heftia
        Bench.Local.Mpeff.Safe
        Bench.Local.Mpeff.Unsafe
        Bench.Local.Mtl
        Bench.Local.Polysemy
        --
        Bench.Nondet.Eff
        Bench.Nondet.Effective
        Bench.Nondet.EffectiveFullyStaged
        Bench.Nondet.EffectiveLightlyStaged
        Bench.Nondet.EffectiveNaive
        Bench.Nondet.FreerSimple
        Bench.Nondet.FusedEffects
        Bench.Nondet.HandrolledListT
        Bench.Nondet.HandrolledLogicT
        Bench.Nondet.Heftia
        Bench.Nondet.Mpeff.Safe
        Bench.Nondet.Mpeff.Unsafe
        Bench.Nondet.MtlListT
        Bench.Nondet.MtlLogict
        Bench.Nondet.Polysemy

benchmark with-o0
    import:         bench-common-o0, bench-heftia, bench-freer-simple, bench-polysemy,
                    bench-fused-effects, bench-effectful, bench-eff, bench-mpeff, bench-mtl,
                    bench-logict, bench-list-t, bench-handrolled, bench-effective, bench-effective-naive
    type:           exitcode-stdio-1.0
    hs-source-dirs: bench
    main-is:        Main.hs
    cpp-options:    -DDISABLE_VERY_DEEP
    -- If your machine has really a lot of memory you can try removing `-DDISABLE_VERY_DEEP`.
    other-modules:
        Bench.Mpeff
        Bench.Catch.VeryDeep.Effective
        Bench.Catch.VeryDeep.EffectiveFullyStaged
        Bench.Catch.VeryDeep.FreerSimple
        Bench.Catch.VeryDeep.Mtl
        Bench.Countdown.VeryDeep.Effective
        Bench.Countdown.VeryDeep.EffectiveFullyStaged
        Bench.Countdown.VeryDeep.FreerSimple
        Bench.Countdown.VeryDeep.Mtl
        Bench.Local.VeryDeep.Effective
        Bench.Local.VeryDeep.EffectiveFullyStaged
        Bench.Local.VeryDeep.FreerSimple
        Bench.Local.VeryDeep.Mtl
        Bench.Nondet.VeryDeep.Effective
        Bench.Nondet.VeryDeep.EffectiveFullyStaged
        Bench.Nondet.VeryDeep.FreerSimple
        Bench.Nondet.VeryDeep.MtlLogict
        Bench.EffectiveFullyStaged
        --
        Bench.Catch.Eff
        Bench.Catch.Effectful
        Bench.Catch.FreerSimple
        Bench.Catch.FusedEffects
        Bench.Catch.Heftia
        Bench.Catch.Mpeff.Safe
        Bench.Catch.Mpeff.Unsafe
        Bench.Catch.Mtl
        Bench.Catch.Polysemy
        Bench.Catch.Handrolled
        Bench.Catch.Effective
        Bench.Catch.EffectiveFullyStaged
        Bench.Catch.EffectiveLightlyStaged
        Bench.Catch.EffectiveNaive
        --
        Bench.Countdown.Eff
        Bench.Countdown.Effective
        Bench.Countdown.EffectiveFullyStaged
        Bench.Countdown.EffectiveLightlyStaged
        Bench.Countdown.EffectiveNaive
        Bench.Countdown.Effectful
        Bench.Countdown.FreerSimple
        Bench.Countdown.FusedEffects
        Bench.Countdown.Handrolled
        Bench.Countdown.Heftia
        Bench.Countdown.Mpeff.Safe
        Bench.Countdown.Mpeff.Unsafe
        Bench.Countdown.Mtl
        Bench.Countdown.Polysemy
        --
        Bench.Local.Effectful
        Bench.Local.Eff
        Bench.Local.Effective
        Bench.Local.EffectiveFullyStaged
        Bench.Local.EffectiveLightlyStaged
        Bench.Local.EffectiveNaive
        Bench.Local.FreerSimple
        Bench.Local.FusedEffects
        Bench.Local.Handrolled
        Bench.Local.Heftia
        Bench.Local.Mpeff.Safe
        Bench.Local.Mpeff.Unsafe
        Bench.Local.Mtl
        Bench.Local.Polysemy
        --
        Bench.Nondet.Eff
        Bench.Nondet.Effective
        Bench.Nondet.EffectiveFullyStaged
        Bench.Nondet.EffectiveLightlyStaged
        Bench.Nondet.EffectiveNaive
        Bench.Nondet.FreerSimple
        Bench.Nondet.FusedEffects
        Bench.Nondet.HandrolledListT
        Bench.Nondet.HandrolledLogicT
        Bench.Nondet.Heftia
        Bench.Nondet.Mpeff.Safe
        Bench.Nondet.Mpeff.Unsafe
        Bench.Nondet.MtlListT
        Bench.Nondet.MtlLogict
        Bench.Nondet.Polysemy
